// <auto-generated />
using System;
using EpsilonWebApp.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpsilonWebApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901123900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EpsilonWebApp.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69eb44c4-7974-4756-ba9b-f94e4290a13f"),
                            Address = "123 Main St",
                            City = "Anytown",
                            CompanyName = "Acme Corporation",
                            ContactName = "John Doe",
                            Country = "USA",
                            Phone = "555-123-4567",
                            PostalCode = "12345",
                            Region = "CA"
                        },
                        new
                        {
                            Id = new Guid("a869edc0-df81-42e1-acbf-af1ef95e235b"),
                            Address = "456 Elm St",
                            City = "Othertown",
                            CompanyName = "Globex Corporation",
                            ContactName = "Jane Smith",
                            Country = "USA",
                            Phone = "555-987-6543",
                            PostalCode = "67890",
                            Region = "NY"
                        },
                        new
                        {
                            Id = new Guid("3c143f46-80ec-4d5d-a067-cd623ccea9fd"),
                            Address = "789 Oak St",
                            City = "Somewhere",
                            CompanyName = "Initech",
                            ContactName = "Bill Lumbergh",
                            Country = "USA",
                            Phone = "555-555-5555",
                            PostalCode = "54321",
                            Region = "TX"
                        },
                        new
                        {
                            Id = new Guid("9a0da791-de71-43a6-bb90-ec3dc9ad3c62"),
                            Address = "321 Pine St",
                            City = "Raccoon City",
                            CompanyName = "Umbrella Corporation",
                            ContactName = "Alice Abernathy",
                            Country = "USA",
                            Phone = "555-111-2222",
                            PostalCode = "98765",
                            Region = "IL"
                        },
                        new
                        {
                            Id = new Guid("7845cc6b-bc07-49cf-8ecb-826b3c04e519"),
                            Address = "1007 Mountain Drive",
                            City = "Gotham",
                            CompanyName = "Wayne Enterprises",
                            ContactName = "Bruce Wayne",
                            Country = "USA",
                            Phone = "555-333-4444",
                            PostalCode = "07001",
                            Region = "NJ"
                        },
                        new
                        {
                            Id = new Guid("49e5a1d7-4eed-4e13-877b-c6055d085d82"),
                            Address = "10880 Malibu Point",
                            City = "Malibu",
                            CompanyName = "Stark Industries",
                            ContactName = "Tony Stark",
                            Country = "USA",
                            Phone = "555-666-7777",
                            PostalCode = "90265",
                            Region = "CA"
                        },
                        new
                        {
                            Id = new Guid("62fda6aa-ba83-45fb-a0d1-cd2ba259ab05"),
                            Address = "20 Ingram Street",
                            City = "New York",
                            CompanyName = "Oscorp",
                            ContactName = "Norman Osborn",
                            Country = "USA",
                            Phone = "555-888-9999",
                            PostalCode = "10001",
                            Region = "NY"
                        },
                        new
                        {
                            Id = new Guid("b6d63e6b-c487-4c77-bfe3-adc71fa9af20"),
                            Address = "1234 Nexus Street",
                            City = "Los Angeles",
                            CompanyName = "Tyrell Corporation",
                            ContactName = "Eldon Tyrell",
                            Country = "USA",
                            Phone = "555-000-1111",
                            PostalCode = "90001",
                            Region = "CA"
                        },
                        new
                        {
                            Id = new Guid("67654f9c-36d5-4acd-9340-5c6f0acf075e"),
                            Address = "5678 Skynet Avenue",
                            City = "San Francisco",
                            CompanyName = "Cyberdyne Systems",
                            ContactName = "Miles Dyson",
                            Country = "USA",
                            Phone = "555-222-3333",
                            PostalCode = "94101",
                            Region = "CA"
                        },
                        new
                        {
                            Id = new Guid("c53ea79d-15d3-444c-bd05-665e56053e4e"),
                            Address = "1 Chocolate Factory Lane",
                            City = "Candyland",
                            CompanyName = "Wonka Industries",
                            ContactName = "Willy Wonka",
                            Country = "USA",
                            Phone = "555-444-5555",
                            PostalCode = "90210",
                            Region = "CA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
